### ISSUE TITLE
Sandbox mode for training days / Reset button

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#144]
And/or reset APIDB from posm-admin.

**Comment by dalekunce** [comment]
:+1:

**Comment by hallahan** [comment]
We could just execute the following steps in `posm-deploy-full.sh` that just rebuilds everything from the data in the AOI. Basically, a reset button that just refers to the data in the AOI directory, thus preventing the need to download the HOT Export over again...

https://github.com/AmericanRedCross/posm-admin/blob/bab07d4fa047990c312b5a35cdd41121fe22b73d/scripts/posm-deploy-full.sh#L37-L59

With this, we might not need an explicit sandbox mode.

**Comment by hallahan** [comment]
I'm thinking the Reset AOI should be just another part of the main POSM AOI Deployment page. It's so similar to the existing Fetch HOT Export workflow, we should just have another option where there is a group of radio buttons, and one of them would be the text input for the HOT URL, and the rest will be choices of existing AOIs on the device. 

If the user puts in a URL, it downloads from HOT like before. If the user selects an existing AOI, then it resets to that previously downloaded deployment.

## Tasks

* [ ] Rename `full-deploy` pages, controller, and route to `aoi-deploy`. That's more descriptive of what we are doing. There is no such thing as a _partial deploy_.
* [ ] Continue using the existing route and controller, and add a `aoi` query param where we can supply the name of an AOI deployment. Then, we can just look and do the reset instead of fetching from HOT by the existence of an `aoi` property instead of a `url` property.
* [ ] Extend the `status` endpoint to also have a list of AOIs currently on the device. This array can be used to populate the radio group.
      - You're actually going to want to look in all of the directories inside of `/opt/data/aoi` and read their `manifest.json`, because you want to show the `title` property in the radio list. The `name` is the name of the directory, and the `title`, which is the "long name" is in the `manifest.json`. The `aoi` query parameter should have the `name`, but the user should see the `title`.
* [ ] Show the active AOI in the left menu. You don't need any sort of dropdown, just the `title` of the active deployment.

I will complete a `posm-aoi-reset.sh` for you.

**Comment by hallahan** [comment]
Here's the Radio Button info in the MDL docs:

https://getmdl.io/components/index.html#toggles-section/radio

**Comment by hallahan** [comment]
Done via https://github.com/AmericanRedCross/posm-admin/pull/3

Thanks @danielduhh
