### ISSUE TITLE
External Field Test 1 Issues

### ISSUE THREAD

**Issue by mojodna** [AmericanRedCross/posm#83]
External issues that need to be addressed by Field Test 1:

- [ ] [CSV output is mis-formatted](https://github.com/fieldpapers/fieldpapers/issues/214)
- [ ] [fp-tasks: convert processes aren't killed when tasks time out](https://github.com/fieldpapers/fieldpapers/issues/213)
- [ ] [Big OSM file does not load in iD editor](https://github.com/AmericanRedCross/OpenMapKitServer/issues/28)
- [ ] [fp-web: Batch uploading of snapshots](https://github.com/fieldpapers/fieldpapers/issues/216)
- [ ] [fp-web: Export data grid (CSV) of snapshot ids corresponding to atlas pages](https://github.com/fieldpapers/fieldpapers/issues/217)
- [ ] OMK Android refactoring to facilitate provisioning

**Comment by mojodna** [comment]
This has been split into individual issues.
